### ISSUE TITLE
Easy creation of Tensors from Arrays needed

### ISSUE THREAD

**Issue by pgawron** [ettersi/Tensors.jl#1]
I belive that this kind of function would be very useful in your package.

```julia
function tensorize(x::AbstractArray, labels::Vector{Symbol})
  modes = [Mode(l,s) for (l,s) in zip(labels,size(x))]
  Tensor(modes,vec(x))
end
```

Could you add it, possibly renaming it, to the package?

**Comment by ettersi** [comment]
Done. The syntax is

    Tensor{T}(mlabel::AbstractVector, x::AbstractArray{T})

e.g. `Tensor([:a,:b,:c],rand(2,3,4))`.
